# Generated by Django 4.0.4 on 2023-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_post_author_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
