# Generated by Django 4.0.4 on 2023-05-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_post_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media',
            new_name='file',
        ),
    ]
