# Generated by Django 4.0.4 on 2023-05-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_media_post_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='image',
        ),
    ]
