# Generated by Django 4.0.4 on 2023-05-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
