# Generated by Django 4.0.4 on 2023-05-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_orderitem_id_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False, null=True, verbose_name='finished'),
        ),
    ]
