# Generated by Django 4.0.4 on 2023-05-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_order_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-completed', 'finished']},
        ),
    ]
